### PR TITLE
HTML5 Entity.setHitBoxTo Fix

### PR DESCRIPTION
**Pull request by forgotten-king**
Fixes a browser platform specific problem(#514) with respect to Std.int not throwing errors but instead overriding **all** passed in defaultValue(s) to zero. This was causing problems for origin x/y being incorrectly overwritten.

Reflect.hasField could have been used but is only expected to work for anonymous structures.

### CODE REVIEW

**Comment by forgotten-king** [comment]
I have a feeling something wrong is going on with my git syncing. All those commits don't look right, but the comparison does say I only changed 1 file like I intended. . .

**Comment by bendmorris** [comment]
You probably need to rebase against the current dev branch.

**Comment by forgotten-king** [comment]
Ah so there is indeed a problem. I'll try fixing it then!

**Comment by MattTuttle** [comment]
Flash is no longer supported in 4.0 so you don't need to check for it in the preprocessor directive.

**Comment by forgotten-king** [comment]
Alright, thanks! That's what I thought but was just being sure. I'll go ahead and remove that once I figure out what's wrong with my repo

**Pull request closed without merging**
