### PR TITLE
Custom vertex attributes

### PR DESCRIPTION
**Pull request by matrefeytontias**
Right now one can set custom vertex attributes of 1 to 4 floats (float, vec2, vec3, vec4 ; basically what the OpenGL specification allows). This should eventually be expanded (especially uniforms, really) into being able to set custom vertex attributes of all possible types.

### CODE REVIEW

**Comment by MattTuttle** [comment]
I'm not sure about adding addVertexAttribData to the generic `prepare*()` classes in RenderBuffer. The reason I made them that way was to remove conditions inside the loop for performance (cut out 5-10% of the cpu time when profiling).

How are you managing to keep the data in sync with DrawCommand? Do you have to override the render function on every object to fill the attribute data buffer in the correct order?

**Comment by matrefeytontias** [comment]
You don't have to override anything for this code to work ; see the Gitter where I posted a screenshot along with the code for its MainScene, which is the only thing I changed.

The point of it and the reason I added addVertexAttribData is that vertex attrib element needs to be interleaved along with the position, texture coords and color elements, hence why it's called after every element of the triangle is pushed, and not after every triangle. As the name implies, it's a vertex-based thing, not triangle-based. An alternative to this I guess would be to detect the end of a DrawCommand and simply copy all vertex attrib data at the end. I'll look into that today.

**Comment by matrefeytontias** [comment]
How is this ?

**Comment by MattTuttle** [comment]
This works for me.

There is still an attribs parameter that needs to be removed from the prepare() functions. Otherwise, this looks good!

**Comment by matrefeytontias** [comment]
That'll do.

**Pull request merged**
