### PR TITLE
Fix Travis.

### PR DESCRIPTION
**Pull request by bendmorris**

### CODE REVIEW

**Comment by ibilon** [comment]
Looks like it's missing hardcoding the version of lime and openfl in haxelib.json.

**Comment by bendmorris** [comment]
Tried that, it seems to be consistently hanging on installing Lime: https://travis-ci.org/HaxePunk/HaxePunk/jobs/164056103#L180 Just bad luck? Also doc generation doesn't seem to be working.

**Comment by ibilon** [comment]
Strange, the only reason would be if haxelib asked something, but that shouldn't happen.
Guess you'll have to remove the `> log.txt || cat log.txt` to find out.

**Comment by bendmorris** [comment]
It's working now. It actually was asking something - "Lime 2.9.1 is already installed, do you want to set this to the current version?" Using `yes` solved it.

**Pull request closed without merging**
