### PR TITLE
Input refactor

### PR DESCRIPTION
**Pull request by bendmorris**
Input is used to check for logical actions, not specific types of input, which Key, Mouse, and individual connected Gamepads can each define. Instead of Input.define, specific define functions are used:

```
Key.define("left", [Key.LEFT, Key.A]);
myGamepad.defineButton("left", [PS3_CONTROLLER.DPAD_LEFT]);
myGamepad.defineAxis("left", PS3_CONTROLLER.LEFT_ANALOGUE_X, -0.1, -1);
Mouse.define("left", MouseButton.LEFT);
```

These can all be polled using a single call: `Input.check("left")`, `Input.pressed("left")`, `Input.released("left")`

Also supports signals at the scene and engine level: `scene.inputPressed.left.bind(myFunction)`

Moves the logic for various input types to their own classes, and fixes Gamepad support for Lime.

For me the biggest break in this change was all the moved mouse logic from `Input`. It might be worth preserving those references, but it might be better to just rip the bandaid off now.

I'd like to eventually add Gesture support as well but that can be done later on.

- [x] Better typed signal implementation
- [x] Add MIGRATION notes
- [x] Standardize when input signals get fired (probably not directly in event handler, maybe at preUpdate step)

### CODE REVIEW

**Comment by MattTuttle** [comment]
I see you created a TypedSignal class. Would it be better to have Signal always typed instead of using `Void->Void`?

**Comment by bendmorris** [comment]
For one example, Lime's Event class (https://github.com/openfl/lime/blob/develop/lime/app/Event.hx) uses a macro for their dispatch method (since macros can accept varargs.) I played around with this briefly but it's a lot of extra complexity for a little more flexibility and wasn't sure it was worth it. Maybe I'll take another look.

**Comment by MattTuttle** [comment]
What about this?

https://gist.github.com/MattTuttle/53845169091880432266660553788243

**Comment by bendmorris** [comment]
I do like your version, I'll incorporate that into this PR.

**Comment by bendmorris** [comment]
There's no good way to test this together with an examples update since Travis doesn't find the new examples commit. To be safe I pushed the examples update first, and if there's a problem I'll just revert it.

**Pull request merged**
