### PR TITLE
Minor Fixes and Features

### PR DESCRIPTION
**Pull request by wselken**
Mostly Text Changes.  Added some more joystick information.
Added Function to run custom code before render executes.

### CODE REVIEW

**Comment by ibilon** [comment]
Word of advice, you should really make a different pull request per feature.

**Comment by bendmorris** [comment]
What's the use case of the "preRender" function? If you need to do something before rendering, couldn't you just override the render method?

**Comment by wselken** [comment]
preRender Might be better named as PostUpdate. and the reason i didn't override the Update function to call the custom code, was because Input.update() is called separately from the update function. so i wanted  all that to be executed before calling my method.  It seemed like a good idea at the time to create a hook for the user to call, but perhaps we could lump the update function together to include Input.update(). as well as any other update logic, so it could be overridden without the need for a hook.

**Comment by bendmorris** [comment]
There's a lot of unrelated stuff in here. I'm going to close this, feel free to reopen individual pull requests if you'd still like to get this merged.

**Pull request closed without merging**
