### PR TITLE
Screenscaling code. -Aspect Ratio and resize fix

### PR DESCRIPTION
**Pull request by whoiam**
This is to fix some problems with screen scaling, and to add more options to screen scaling.

In the old code resizing the window can effect HXP width and height.
The old HXP.resize()  also didn't seem to work very well in my experience.

This allows for different screen scaling modes to be easily used by changing the new HXP.screenscaleMode.
Options:
Force - Scales disregarding aspect ratio. How the scale functioned functioned previously
AspectRatio - Scales with aspect ratio. The default setting.
Multiples - Scales by multiples of screenscaleMultiples. For example use to keep pixels scaled evenly.
Custom - Use screenscale variables and set the scale yourself.
Dynamic - The window sets the game width and height and scale is applied from screenscale.

The code also places the game screen in the center of the window.

I wasn't sure where I should put the new variables in the code so I just put them above the resize function.

### CODE REVIEW

**Comment by christopf** [comment]
I first thought after your comment, it maybe a version problem, but it isn't.
For me this fix is totally working.
Maybe you give it  another try?

**Comment by ibilon** [comment]
@christopf I'll be able to retest in about a week, but it's strange I couldn't make it work and you could, could you post a sample on how you used it?

**Comment by ibilon** [comment]
Just realized it's targeted to the master branch, and there's merge conflicts.

**Comment by christopf** [comment]
You still want a sample?

**Comment by ibilon** [comment]
No, it'll be too much trouble to merge this, and it there's already something different planned for haxepunk 3.

**Pull request closed without merging**
