### PR TITLE
Build with no backend

### PR DESCRIPTION
**Pull request by MattTuttle**
I added preprocessor directives to remove the need for a backend. It's a little messy at the moment but this is a big step to having multiple backends.

### CODE REVIEW

**Comment by bendmorris** [comment]
Awesome. What do you think about organizing the `App` definitions in separate backend packages:

```haxe
package haxepunk.backends.openfl;

class OpenFlApp
{
    // ..
}
```

And then making App.hx just a conditional typedef with a fallback definition?

```haxe
#if (lime || nme)
typedef App = haxepunk.backends.openfl.OpenFlApp;
#else
class App
{
    // ...
}
#end
```

I imagine we'll want to do something similar to abstract asset managers, textures, etc. for each backend, and I would vote to group all of those into one package per backend.

**Comment by MattTuttle** [comment]
I think that's a good idea.

I don't like the way I had to pass an `Engine` instance to the `App` parent. It feels dirty to me. I couldn't figure out a better way to separate them without completely rewriting pieces.

**Comment by bendmorris** [comment]
The rest of the issues codeclimate flagged are due to limitations of Haxe checkstyle. If this is ready to merge, it looks good to me.

**Comment by bendmorris** [comment]
Hm, actually Travis doesn't seem to be flagging failures properly: https://travis-ci.org/HaxePunk/HaxePunk/jobs/307665549

>   ../haxepunk/backend/lime/GLInternal.hx:3: characters 7-30 : Type not found : lime.graphics.opengl.GL
> Error: Error compiling hxml for neko

**Comment by bendmorris** [comment]
:+1: looks like it's working now. The shell script wasn't failing when commands failed, and mcover now breaks since it tries to include files from every backend. (Coverage wasn't working anyway, so no big deal.)

**Comment by MattTuttle** [comment]
I think this is ready to merge. Thanks for fixing it up!

**Pull request merged**
