### PR TITLE
Better inheritance and extension

### PR DESCRIPTION
**Pull request by cjmxp**
Better inheritance and extension

### CODE REVIEW

**Comment by IkonOne** [comment]
@bendmorris I think a standardized way to validate parameters could be helpful.  The way Flambe did it was with an Assert class that stripped out the error checks in release builds: https://github.com/aduros/flambe/blob/master/src/flambe/util/Assert.hx

**Comment by bendmorris** [comment]
@cjmxp can you share some context for this change? What's your use case for an AtlasData with no texture?

**Comment by cjmxp** [comment]
```
class MyAtlasData extends AtlasData implements HttpAsset{
public function new(){
super(null,name)
}
public function load(url:String):Void{
     this.texture = BitmapData.fromImage(lime.graphics.Image.fromBytes(Bytes.ofString(Http.requestUrl(url))));
}

}

var httploader  = new MyAtlasData();
httploader.load("http://xxx.com/aaa.jpg");
```

**Comment by bendmorris** [comment]
That's clever but I'm not sure it's something we can totally support, since other parts of the code might try to use the texture or width/height before it's ready. What if a wrapper implemented HttpAsset instead, and generated the AtlasData only after the resource was loaded?

**Comment by bendmorris** [comment]
@IkonOne I think that's a great idea. I probably won't get to it right away but a PR would be welcome.

**Comment by IkonOne** [comment]
@cjmxp I'm not sure if this is still possible, but you might be able to try using a null texture.  There used to be a `Texture.nullTexture` static variable for just this, but it has been removed.  I'd imagine you could probably still do `new Texture(null)`

https://github.com/HaxePunk/HaxePunk/commit/d45fa45664a626b99a0bf3d503e5b56771137316#diff-a939bb54eef009effc1046a166774800L19

**Comment by bendmorris** [comment]
`new Texture(null)` won't work since Texture is an abstract. `new Texture(null)` is the same as `null` at runtime. We don't need a `Texture.nullTexture` since `null` is now a null texture, but we might want to add null checks into the Texture methods, which would solve @cjmxp's problem.

**Comment by cjmxp** [comment]
```
import core.net.HttpAssets;
import core.vo.GAtlasData;
import haxepunk.graphics.atlas.IAtlasRegion;
import haxepunk.math.Rectangle;
import haxepunk.Camera;
import haxepunk.math.Vector2;
import haxepunk.Graphic;

class GTile extends Graphic{
    public var url(default,default):String = "";
    public var pkg(default,default):String ="";
    public var atlas:GAtlasData = null;
    private var region:IAtlasRegion = null;
    public function new() {
        super();
        alpha = 1;
        color = 0xFFFFFF;
    }
    public function load(url:String,pkg:String):Void
    {
        this.pkg=pkg;
        this.url=url;
        this.atlas=GAtlasData.getAtlasDataByUrl(url);
        this.atlas.url=url;
        this.atlas.pkg=pkg;
        HttpAssets.instance.load(this.atlas);
    }
    override public function render(point:Vector2, camera:Camera){
        if(this.region==null){
            if(this.atlas!=null && this.atlas.texture!=null){
                this.region = this.atlas.createRegion(new Rectangle(0, 0, this.atlas.width, this.atlas.height));
            }
            return;
        }
        var fsx = 1;//camera.fullScaleX;
        var fsy = 1;//camera.fullScaleY;

        var x = floorX(camera, x);
        var y = floorY(camera, y);

        _point.x = floorX(camera, point.x) - floorX(camera, camera.x * scrollX) + x;
        _point.y = floorY(camera, point.y) - floorY(camera, camera.y * scrollY) + y;

        var clipRect = screenClipRect(camera, _point.x, _point.y);
        this.region.draw(_point.x * fsx, _point.y * fsy, fsx, fsy, 0,color, alpha,shader, smooth, blend, clipRect, flexibleLayer);
    }

    public override function destroy():Void
    {
        super.destroy();
        region.destroy();
    }
}
```

**Pull request closed without merging**
